manual_regions <- list()

manual_regions[['middle_east_prio']] <- c("Yemen",
                      "Oman",
                      "Iran (Islamic Republic of)",
                      "Israel",
                      "Qatar",
                      "Bahrain",
                      "Syrian Arab Republic",
                      "Turkey",
                      "Palestine, State of",
                      "United Arab Emirates",
                      "Saudi Arabia",
                      "Kuwait",
                      "Iraq") %>% countrycode(origin = "country.name", destination = "iso3n")


manual_regions[['asia_rest_prio']] <- c("Micronesia (Federated States of)",
                    "Jordan",
                    "Mongolia",
                    "China",
                    "Christmas Island",
                    "Armenia",
                    "India",
                    "Georgia",
                    "Pitcairn",
                    "Heard Island and McDonald Islands",
                    "Japan",
                    "French Polynesia",
                    "Kazakhstan",
                    "Uzbekistan",
                    "Macao",
                    "Kyrgyzstan",
                    "Palau",
                    "Papua New Guinea",
                    "Malaysia",
                    "Myanmar",
                    "Iraq",
                    "Tonga",
                    "Vanuatu",
                    "New Zealand",
                    "Timor-Leste",
                    "Sri Lanka",
                    "Thailand",
                    "Fiji",
                    "Marshall Islands",
                    "Bangladesh",
                    "Turkmenistan",
                    "Korea (Democratic People's Republic of)",
                    "Cocos (Keeling) Islands",
                    "Samoa",
                    "Northern Mariana Islands",
                    "American Samoa",
                    "Brunei Darussalam",
                    "Cambodia",
                    "United States Minor Outlying Islands",
                    "Bhutan",
                    "Tuvalu",
                    "Singapore",
                    "Lao People's Democratic Republic",
                    "Indonesia",
                    "Hong Kong",
                    "Australia",
                    "Guam",
                    "Pakistan",
                    "Tokelau",
                    "Solomon Islands",
                    "Niue",
                    "Cook Islands",
                    "Viet Nam",
                    "Korea (Republic of)",
                    "Philippines",
                    "Lebanon",
                    "Cyprus",
                    "Azerbaijan",
                    "Kiribati",
                    "Nepal",
                    "Afghanistan",
                    "New Caledonia",
                    "Taiwan, Province of China",
                    "Norfolk Island",
                    "Wallis and Futuna",
                    "Maldives",
                    "Tajikistan",
                    "Nauru"
                    ) %>% countrycode(origin = "country.name", destination = "iso3n")
