proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://landportal.org/sites/landportal.org/files/styles/220heightmax/public/Screen%20Shot%202017-07-17%20at%2016.42.25.png
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: name1
    password: password
    groups: admins
  - name: name2
    password: password
  docker:
      internal-networking: true
  specs:
  - id: hdr_app_v2
    display-name: CAP Application
    description: Application for those curious about conflict
    container-cmd: ["R", "-e", "shiny::runApp('/root/CAPA', host = '0.0.0.0', port = 3838, launch.browser = FALSE)"]
    container-image: container/image
    container-network: shinynet
    container-volumes: [ "/home/andara/CAPA/hdr_app_v2/CAPA:/root/CAPA" ]
logging:
  file:
    shinyproxy.log
